"""empty message

Revision ID: 5f5d0c73297b
Revises: bd9f0b5b0136
Create Date: 2024-12-17 02:09:04.120825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5d0c73297b'
down_revision = 'bd9f0b5b0136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('zipcode', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('birstday', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birstday')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
